name: Path-gen test

permissions:
  contents: read

on:
  workflow_dispatch:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
#       - name: Checkout vul-parser-benchmark
#         uses: actions/checkout@v4
#         with:
#           repository: 'thebesttv/vul-parser-benchmark'
#           path: 'graph-generation/vul-parser-benchmark'
      - name: Install dependencies
        run: sudo apt-get install -y ninja-build
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          create-symlink: true
          variant: sccache
      - name: Generate CMake
        run: |
          ./build-release.sh
      - name: Build tool
        run: |
          ./graph-generation/tool -h
      - name: Run test
        run: |
          ./graph-generation/test.py
