name: Path-gen test

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
  push:

jobs:
  create-appimage:
    runs-on: ubuntu-20.04
    name: Create AppImage
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get install -y ninja-build fuse
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: ccache
        # 暂时用 cache 加速
        uses: hendrikmuhs/ccache-action@v1
        with:
          variant: sccache
      - name: Generate CMake
        run: |
            ./build-release.sh \
              -DCMAKE_C_COMPILER_LAUNCHER=sccache \
              -DCMAKE_CXX_COMPILER_LAUNCHER=sccache
      - name: Build tool
        run: ./graph-generation/tool -h

      - name: Get linuxdeploy
        run: |
          wget -O linuxdeploy \
            https://github.com/linuxdeploy/linuxdeploy/releases/download/1-alpha-20240109-1/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy
      # - name: Create AppImage
      #   run: ./create-appimage.sh
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 1440

  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Quick: 缓存、只跑最基本的测试
        # Medium: 缓存、跑所有测试
        # Full: 从头编译、跑所有测试
        test_type: [Quick, Medium, Full]
    name: ${{ matrix.test_type }} test
    steps:
      - name: Maximize build space
        # 由于真实项目基于 Docker image，所以需要更多的空间
        if: ${{ matrix.test_type != 'Quick' }}
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 35840
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get install -y ninja-build
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: ccache
        # Quick 和 Medium 版本使用 ccache 加速编译，Full 版从头编译
        if: ${{ matrix.test_type != 'Full' }}
        uses: hendrikmuhs/ccache-action@v1
        with:
          variant: sccache
      - name: Pull Docker images in background
        # 真实项目需要 Docker image
        if: ${{ matrix.test_type != 'Quick' }}
        run: |
          docker pull thebesttv/arch:php &
          docker pull thebesttv/arch:snd &
      - name: Generate CMake
        run: |
          if [ "${{ matrix.test_type }}" != "Full" ]; then
            ./build-release.sh \
              -DCMAKE_C_COMPILER_LAUNCHER=sccache \
              -DCMAKE_CXX_COMPILER_LAUNCHER=sccache
          else
            ./build-release.sh
          fi
      - name: Build tool
        run: |
          ./graph-generation/tool -h
      - name: Pull Docker images
        # 真实项目需要 Docker image
        if: ${{ matrix.test_type != 'Quick' }}
        run: |
          docker pull thebesttv/arch:php
          docker pull thebesttv/arch:snd
          df -h
      - name: Run test
        run: |
          if [ "${{ matrix.test_type }}" == "Quick" ]; then
            ./graph-generation/test.py
          else
            ./graph-generation/test.py -a
          fi
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        timeout-minutes: 1440
