name: Path-gen test

permissions:
  contents: read

on:
  workflow_dispatch:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 35840
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      - name: Checkout repo
        uses: actions/checkout@v4
#       - name: Checkout vul-parser-benchmark
#         uses: actions/checkout@v4
#         with:
#           repository: 'thebesttv/vul-parser-benchmark'
#           path: 'graph-generation/vul-parser-benchmark'
      - name: Install dependencies
        run: sudo apt-get install -y ninja-build
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          variant: sccache
      - name: Generate CMake
        run: |
          ./build-release.sh \
              -DCMAKE_C_COMPILER_LAUNCHER=sccache \
              -DCMAKE_CXX_COMPILER_LAUNCHER=sccache
      - name: Build tool
        run: |
          ./graph-generation/tool -h
      - name: Pull Docker images
        run: |
          docker pull thebesttv/arch:php
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 1440
      - name: Run test
        run: |
          ./graph-generation/test.py
