name: Path-gen test

permissions:
  contents: read

on:
  workflow_dispatch:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_type: [Quick, Full]
    name: ${{ matrix.test_type }} test
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 35840
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get install -y ninja-build
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: ccache
        # Quick 版本使用 ccache 加速编译，Full 版从头编译
        if: ${{ matrix.test_type == 'Quick' }}
        uses: hendrikmuhs/ccache-action@v1
        with:
          variant: sccache
      - name: Generate CMake
        run: |
          if [ "${{ matrix.test_type }}" == "Quick" ]; then
            ./build-release.sh \
              -DCMAKE_C_COMPILER_LAUNCHER=sccache \
              -DCMAKE_CXX_COMPILER_LAUNCHER=sccache
          else
            ./build-release.sh
          fi
      - name: Build tool
        run: |
          ./graph-generation/tool -h
      - name: Pull Docker images
        # Full 版才需要 Docker image
        if: ${{ matrix.test_type == 'Full' }}
        run: |
          docker pull thebesttv/arch:php
      - name: Run test
        run: |
          if [ "${{ matrix.test_type }}" == "Full" ]; then
            ./graph-generation/test.py -a
          else
            ./graph-generation/test.py
          fi
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
        timeout-minutes: 1440
