name: Path-gen test

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install Ninja
        run: sudo apt-get install -y ninja-build
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Generate CMake
        run: |
          ./build-release.sh
      - name: Build tool
        run: |
          ./graph-generation/tool -h
